### ISSUE TITLE
Feature request: Make water acidic

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#15]
Just a thought...

It would be a great addition if water were acidic. Variants:
- only in biomes where acid rain occurs, or specified biomes
- only specific types of water: ocean, river, ponds
- probably more

Sample config.yml
```
Acidrain:
...
  Other:
# Currently, MakeWaterAcidic is invoked only during acid rain.
# This should be removed in favor of Acidwater below.
    MakeWaterAcidic: true
...
AcidWater:
  enable: true
  DisabledInClaims: false
  MakeWaterAcidic:
# All ocean biomes, or possible separate them
    - Oceans: true
# All rivers
    - Rivers: true
# Ponds are small pools of water, enclosed. "Small" should be defined.
    - Ponds: true
  Worlds:
    - 'world'
  #World Guard support. Put your region names which you want acid water to be disabled.
  DisabledRegions:
    - 'none'
  #Chance of the acid water in any water chunk (interpreted as a percentage).
  Chance: 50
  #Biomes in which the acid water does not occur.
  DisabledBiomes:
    - 'Frozen River'
  #Use this if you want acid water to give potion effects to your players.
  PotionEffects:
    Enabled: true
    Chances:
      Chance: 100
      ChanceTimer: 30
    Effects:
      - 'Confusion'
      - 'Hunger'
      - 'Slow'
      - 'Weakness'
    EffectDuration: 25
    EffectPotentcy: 1
  Other:
    CantKill: false
```

**Comment by SlimeDog** [comment]
That depends. If you implemented
> Ponds: true

it could be a very long list. It would probably be better to just use the AcidRain biomes blacklist by default, then add others if desired.

**Comment by MostWantedMinx** [comment]
Yeah I think I'll just run it off the AcidRain biomes blacklist instead ^^

**Comment by MostWantedMinx** [comment]
Actually, upon closer inspection, it should already do this regardless. Although, do correct me if I am incorrect. Also, if you'd like to join my new discord server, here's a link https://discordapp.com/invite/zNtFN3m

**Comment by SlimeDog** [comment]
Only when it's raining. I would like acid water all the time (in selected worlds and biomes and regions).

**Comment by SlimeDog** [comment]
Perhaps a simpler approach:
```
Acidrain:
  MakeWaterAcidic:
    - enable: true
    - AcidOceans: true
    - AcidRivers: true
    - AcidPonds: true
```
