### ISSUE TITLE
Feature request: Potion effect delay

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#21]

**Comment by SlimeDog** [comment]
Random thought...

```
Acidrain:
  PotionEffects:
    #Delay effects for a number of seconds
    Delay: 1
```

This would allow a very quick run (between doors, say) without effect.
