### ISSUE TITLE
No damage or potion effects from acid rain

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#23]
Spigot 1.13.1 latest
PWP 2.0.3

Now acid water causes damage, but acid rain causes neither damage nor potion effects.

config.yml (comments and Temperature config elided)
```
Config-Version: 2.0.0

GeneralSettings:
  DisableWeatherWorlds:
    - 'none'
  ChangeWorld:
    InvulnerabilityTime: 8
  HideSpigotURL: true
  UseCustomMobs: false

Acidrain:
  Enabled: true
  DisabledInClaims: false
  Worlds:
    - 'world_yellowdog'
  DisabledRegions:
    - 'none'
  Chances:
    ChanceToStart: 100
    ChanceTimer: 300
  StormInformation:
    StormTime: 180
    DamageInterval: 1
    BaseDamage: 1
  Other:
    DealKnockback: false
    MakeWaterAcidic:
      Enabled: true
      AlwaysActive: true
      AlwaysActiveInRain: false
      DamageInterval: 1
    AllStormsAcid: true
    TitleMessageNotfications: false
    CantKill: false
  DisabledBiomes:
    - 'NETHER'
    - 'BADLANDS'
    - 'DESERT'
    - 'DESERT LAKES'
    - 'ERODED BADLANDS'
    - 'PLATEAU'
    - 'MODIFIED BADLANDS PLATEAU'
    - 'MODIFIED PLATEAU'
    - 'SAVANNA'
    - 'SHATTERED SAVANNA'
    - 'SHATTERED SAVANNA PLATEAU'
    - 'WOODED BADLANDS PLATEAU'
  PotionEffects:
    Enabled: true
    Chances:
      Chance: 100
      ChanceTimer: 30
    Effects:
      - 'Confusion'
      - 'Hunger'
      - 'Slow'
      - 'Weakness'
    EffectDuration: 5
    EffectPotentcy: 1
```
