### ISSUE TITLE
No potion effects

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#6]
Spigot 1.13.1 latest
PWP 1.1.0

Player is standing outside. I start acid rain, confirmed at console/log.
```
[08:16:26 INFO]: CONSOLE issued server command: /storm world_yellowdog storm 60
[08:16:26 INFO]: [Skript] [start-acid-rain.sk] Weather changed from clear to rain in world_yellowdog
[08:16:26 INFO]: You set the weather to storm in world_yellowdog for 60 seconds.
[08:16:26 INFO]: PyroWeather Acidrain has started in the worlds: [world_yellowdog]
```
Player sees acid rain (special resourcepack, so we can tell). But player does not suffer potion effects (per configuration below). They did suffer potion effects on Spigot 1.12.2 with PW 2.0.3.

config.yml
```
Config-Version: 1.1.0

#General Settings for the entire plugin
GeneralSettings:
  #These worlds will have no weather at all. This includes: rain, snow, lightning storms and all custom storms.
  DisableWeatherWorlds:
    - 'none'
  #Some options when the player changes a world.
  ChangeWorld:
    InvulnerabilityTime: 8
  #Ability to hide the spigot url. (If you want to hide this from your players.)
  HideSpigotURL: true
  #Ability to enable and disable custom mobs. (WARNING: This will remove a lot of functonality from the plugin.)
  UseCustomMobs: false


#Acid rain information
Acidrain:
  Enabled: true
  #This is for the GriefPrevention plugin. Settings this to false will make it so players do not take damage in claims.
  DisabledInClaims: false
  #Worlds in which acidrain is enabled in
  Worlds:
    - 'world_yellowdog'
  #World Guard support. Put your region names which you want acid rain to be disabled. It will still rain here but will not deal damage or give effects to players.
  DisabledRegions:
    - 'none'
  #Chance of the acidrain starting and how long it will last.
  Chances:
    ChanceToStart: 100
    ChanceTimer: 300
  #General storm information, how long it lasts and how much damage it deals including the interval of the damage.
  StormInformation:
    StormTime: 180
    DamageInterval: 1
    BaseDamage: 1
  #Some options which you can enable / disable while acidrain is active.
  Other:
    DealKnockback: false
    MakeWaterAcidic: true
    AllStormsAcid: true
    TitleMessageNotfications: false
  #Biomes in which the acidrain is disabled.
  # YellowDog spawn is in a Savanna biome, so we want acid rain there.
  DisabledBiomes:
    - 'Badlands'
    - 'Desert'
    - 'Desert Lakes'
    - 'Eroded Badlands'
    - 'Plateau'
    - 'Modified Badlands Plateau'
    - 'Modified Plateau'
    - 'Wooded Wooded Badlands Plateau'
#   - 'Savanna'
    - 'Shattered Savanna'
    - 'Shattered Savanna Plateau'
    - 'Wooded Badlands Plateau'
  #Use this if you want acidrain to give potion effects to your players.
  PotionEffects:
    Enabled: true
    Chances:
      Chance: 100
      ChanceTimer: 30
    Effects:
      - 'Confusion'
      - 'Hunger'
      - 'Slow'
      - 'Weakness'
    EffectDuration: 25
    EffectPotentcy: 1
```
